=== zzcahary/wsd/test/web/WEB-INF/reservationSchema.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
<xs:element name="reservations">
    <xs:complexType>
        <xs:sequence>
            <xs:element name = "reservation" minOccurs="2" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element type="xs:String" name="title"/>
                        <xs:element type="xs:String" name="username"/>
                        <xs:element type="xs:String" name="email"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== zzcahary/wsd/test/build/web/WEB-INF/reservations.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="reservation.xsl"?>
<reservations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/Users/zack/Desktop/test/src/java/reservationSchema.xsd">
  <reservation>
    <title>Harry-Potter</title>
    <username>Zac</username>
    <email>tom@tom.com</email>
  </reservation>
  <reservation>
    <title>Harry Poter</title>
    <username>lam</username>
    <email>lam@gmail.com</email>
  </reservation>
  <reservation>
    <title>Love</title>
    <username>heng</username>
    <email>heng@gmail.com</email>
  </reservation>
  <reservation>
    <title>UTS</title>
    <username>abc123</username>
    <email>abc123@gmail.com</email>
  </reservation>
</reservations>
